services:
  web-server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    ports:
      - 8055:8050
    depends_on:
      - callback-worker
      - query-worker
      - cache
    env_file:
      - ./env.list
    environment:
      REDIS_SERVICE_HOST: cache
      REDIS_SERVICE_PORT: 6388
    restart: always

  callback-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.worker
    depends_on:
      - cache
    env_file:
      - ./env.list
    environment:
      REDIS_SERVICE_HOST: cache
      REDIS_SERVICE_PORT: 6388
    restart: always

  query-worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.worker
    command: ["celery", "-A", "app:celery_app", "worker", "--loglevel=INFO", "-Q", "data"]
    depends_on:
      - cache
    env_file:
      - ./env.list
    environment:
      REDIS_SERVICE_HOST: cache
      REDIS_SERVICE_PORT: 6388
    restart: always

  cache:
    image: redis
    ports:
      - 6380:6380
    restart: always

  flower:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.flower
    depends_on:
      - callback-worker
      - query-worker
      - cache
      - web-server
    env_file:
      - ./env.list
    environment:
      REDIS_SERVICE_HOST: cache
      REDIS_SERVICE_PORT: 6388
    ports:
      - 5557:5557
